apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox-hpa
  namespace: maybank-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busybox-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  # Adjust based on your requirements
