apiVersion: v1
kind: Namespace
metadata:
  name: maybank-prod
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: busybox
#   name: busybox
#   namespace: maybank-prod
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: busybox
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate  
#   template:
#     metadata:
#       labels:
#         app: busybox
#     spec:
#       containers:
#       - image: busybox
#         command: ["sleep", "3600"]
#         volumeMounts:
#           - mountPath: /logs
#             name: cliapp
#         env:
#         - name: spring.profiles.active
#           valueFrom:
#             configMapKeyRef:
#               key: spring.profiles.active
#               name: biapay-profile
#         resources:
#           requests:
#             memory: "600Mi"
#             cpu: "300m"
#           limits:
#             memory: "800Mi"
#             cpu: "600m"
#         name: busybox
#         ports:
#         - containerPort: 80 # this port is not useless in busybox
#           protocol: TCP
#       imagePullSecrets:
#       - name: harbor-pull-secret
#       volumes:
#         - name: cliapp
#           nfs:
#             path: /kubedata/logs
#             server: biapay-prod-efs.local.vpc